# Generated by Django 4.1.7 on 2023-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="totalInCent",
            new_name="totalInCents",
        ),
    ]
