# Generated by Django 4.1.7 on 2023-03-20 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_order_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="totalInCents",
            new_name="total_in_cents",
        ),
    ]
